addons:
ssh_known_hosts:
  - 106.12.27.104
before_install:
  - openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
script:
  - ssh root@106.12.27.104 -o StrictHostKeyChecking=no 'cd /root/forum-backend && git remote update origin --prune && mvn clean install && mv -f target/demo-0.0.1-SNAPSHOT.jar /root/back-end/ && cd /root/back-end && docker-compose up'
